default:
  image: alpine:3.18

stages:
  - lint

magik-lint:
  stage: lint
  script:
    - apk add --no-cache curl=8.2.1-r0 openjdk17-jre-headless=17.0.8_p7-r0
    - mkdir -p /tmp/magik-lint
    - curl -sfL -o /tmp/magik-lint/magik-lint-0.7.1.jar https://github.com/StevenLooman/magik-tools/releases/download/0.7.1/magik-lint-0.7.1.jar
    - mkdir -p /tmp/reviewdog
    - curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b /tmp/reviewdog v0.15.0
    - java -jar /tmp/magik-lint/magik-lint-0.7.1.jar --column-offset +1 --msg-template "\${path}:\${line}:\${column}:\${msg} (\${symbol})" ${CI_PROJECT_DIR} | /tmp/reviewdog/reviewdog -efm="%f:%l:%c:%m" -name="magik-lint" -reporter=gitlab-mr-discussion -level=error -filter-mode=added -fail-on-error=false
